


import { Engineer, Supervisor, Team, UserRole, Translations, Language, ShiftType, Employee } from './types';

export const APP_NAME = "Control Shift Pro"; // Kept for EN version consistency
export const APP_NAME_AR = "كنترول شيفت برو"; // Arabic App Name

export const COMPANY_NAME_EN = "United Gas Derivatives Company | Control | Damietta Site";
export const COMPANY_NAME_AR = "الشركة المتحدة لمشتقات الغاز | كنترول | موقع دمياط";

export const ENGINEERS: Engineer[] = [
  { id: 'eng1', name: 'أحمد بيه سيد', role: UserRole.Engineer, email: 'ahmed.sayed@ugdc.com', phone: '01001234567' },
  { id: 'eng2', name: 'باشمهندس هيثم دويدار', role: UserRole.Engineer, email: 'haitham.doweidar@ugdc.com', phone: '01002345678' },
  { id: 'eng3', name: 'أحمد أفندي عوض', role: UserRole.Engineer, email: 'ahmed.awad@ugdc.com', phone: '01003456789' },
  { id: 'eng4', name: 'أستاذ محمد رياض', role: UserRole.Engineer, email: 'mohamed.riad@ugdc.com', phone: '01004567890' },
  { id: 'eng5', name: 'كريم باشا مجاهد', role: UserRole.Engineer, email: 'karim.megahed@ugdc.com', phone: '01005678901' },
];

export const SUPERVISORS: Supervisor[] = [
  { id: 'sup1', name: 'الأسطى أحمد عراقي', role: UserRole.Supervisor, teamId: 'team1', email: 'ahmed.iraqi@ugdc.com', phone: '01221234567' },
  { id: 'sup2', name: 'الريس عبد الناصر فتحي', role: UserRole.Supervisor, teamId: 'team2', email: 'abdelnasser.fathy@ugdc.com', phone: '01222345678' },
  { id: 'sup3', name: 'المعلم محمد دسوقي', role: UserRole.Supervisor, teamId: 'team3', email: 'mohamed.desouky@ugdc.com', phone: '01223456789' },
  { id: 'sup4', name: 'كابتن أيمن يونس', role: UserRole.Supervisor, teamId: 'team4', email: 'ayman.younes@ugdc.com', phone: '01224567890' },
];

export const EMPLOYEES_TEAM1: Employee[] = [
  { id: 'emp1-1', name: 'محمد حسن (أبو علي)', role: UserRole.Employee, teamId: 'team1', email: 'mohamed.hassan@ugdc.com', phone: '01111234567' },
  { id: 'emp1-2', name: 'شاكر إبراهيم (البرنس)', role: UserRole.Employee, teamId: 'team1', email: 'shaker.ibrahim@ugdc.com', phone: '01112345678' },
  { id: 'emp1-3', name: 'أحمد درويش (الدرويش)', role: UserRole.Employee, teamId: 'team1', email: 'ahmed.darwish@ugdc.com', phone: '01113456789' },
];

export const EMPLOYEES_TEAM2: Employee[] = [
  { id: 'emp2-1', name: 'سيد طنطاوي (العمدة)', role: UserRole.Employee, teamId: 'team2', email: 'sayed.tantawy@ugdc.com', phone: '01114567890' },
  { id: 'emp2-2', name: 'علاء عبد العزيز (زيزو)', role: UserRole.Employee, teamId: 'team2', email: 'alaa.abdelaziz@ugdc.com', phone: '01115678901' },
  { id: 'emp2-3', name: 'أحمد رجب (رجبونا)', role: UserRole.Employee, teamId: 'team2', email: 'ahmed.ragab@ugdc.com', phone: '01116789012' },
];

export const EMPLOYEES_TEAM3: Employee[] = [
  { id: 'emp3-1', name: 'شعبان إبراهيم (شعبولا)', role: UserRole.Employee, teamId: 'team3', email: 'shaban.ibrahim@ugdc.com', phone: '01117890123' },
  { id: 'emp3-2', name: 'محمد يحيى (أبو حميد)', role: UserRole.Employee, teamId: 'team3', email: 'mohamed.yahya@ugdc.com', phone: '01118901234' },
  { id: 'emp3-3', name: 'إبراهيم السحراوي (السحروي)', role: UserRole.Employee, teamId: 'team3', email: 'ibrahim.sahrawy@ugdc.com', phone: '01119012345' },
];

export const EMPLOYEES_TEAM4: Employee[] = [
  { id: 'emp4-1', name: 'ماجد سعيد (أبو المجد)', role: UserRole.Employee, teamId: 'team4', email: 'maged.saeed@ugdc.com', phone: '01120123456' },
  { id: 'emp4-2', name: 'محمد عبد الفتاح (الفتاح)', role: UserRole.Employee, teamId: 'team4', email: 'mohamed.abdelftah@ugdc.com', phone: '01121234567' },
  { id: 'emp4-3', name: 'أحمد عطية (أبو عطوة)', role: UserRole.Employee, teamId: 'team4', email: 'ahmed.attia@ugdc.com', phone: '01122345678' },
];

export const TEAMS: Team[] = [
  { id: 'team1', name: 'فريق الأبطال (بتوع عراقي)', supervisorId: 'sup1', memberIds: EMPLOYEES_TEAM1.map(e => e.id) },
  { id: 'team2', name: 'فريق الوحوش (جماعة ناصر)', supervisorId: 'sup2', memberIds: EMPLOYEES_TEAM2.map(e => e.id) },
  { id: 'team3', name: 'فريق النسور (شلة دسوقي)', supervisorId: 'sup3', memberIds: EMPLOYEES_TEAM3.map(e => e.id) },
  { id: 'team4', name: 'فريق العتاولة (رجال يونس)', supervisorId: 'sup4', memberIds: EMPLOYEES_TEAM4.map(e => e.id) },
];

// Shift times
export const MORNING_SHIFT_START = "7:30 صباحاً";
export const MORNING_SHIFT_END = "7:30 مساءً";
export const EVENING_SHIFT_START = "7:30 مساءً";
export const EVENING_SHIFT_END = "7:30 صباحاً";

export const CURRENT_SHIFT_ASSIGNMENTS = [
    { teamId: 'team1', shiftType: ShiftType.Evening },
    { teamId: 'team2', shiftType: ShiftType.Morning },
    { teamId: 'team3', shiftType: ShiftType.Off },
    { teamId: 'team4', shiftType: ShiftType.Off },
];

export const initialTranslations: Translations = {
  [Language.EN]: {
    appName: APP_NAME,
    companyName: COMPANY_NAME_EN,
    dashboard: 'Dashboard',
    shifts: 'Shifts',
    tasks: 'Daily Tasks',
    ships: 'Ship Management',
    settings: 'Settings',
    notifications: 'Notifications',
    language: 'Language',
    english: 'English',
    arabic: 'Arabic',
    welcomeMessage: `Welcome to ${APP_NAME}! Manage your shifts and tasks efficiently. Let's get to work, ya rayes!`,
    currentShift: 'Current Shift',
    morningShift: `Morning Shift (${MORNING_SHIFT_START} - ${MORNING_SHIFT_END})`,
    eveningShift: `Evening Shift (${EVENING_SHIFT_START} - ${EVENING_SHIFT_END})`,
    teamOnDuty: 'Team on Duty',
    supervisor: 'Supervisor',
    members: 'Members',
    addTask: 'Add Task',
    taskDescription: 'Task Description...',
    saveTask: 'Save Task',
    noTasks: 'No tasks for today... ya reggala, اشتغلوا شوية!',
    shipName: 'Ship Name',
    shipStatus: 'Status',
    cargoType: 'Cargo Type',
    quantityRemaining: 'Qty Remaining',
    quantityPerHour: 'Qty/Hour',
    eta: 'ETA/ETD',
    pumps: 'Pumps',
    noShips: 'No ships currently managed. El donya nayma keda leh?',
    userRole: 'User Role',
    selectRole: 'Select your role',
    employee: 'Employee',
    supervisorRole: 'Supervisor',
    engineer: 'Engineer',
    engineersList: 'Engineers',
    supervisorsList: 'Supervisors & Teams',
    appTheme: 'App Theme',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    darkModeDescription: 'For night owls and cool folks.',
    comedyLevel: 'Comedy Level (Notifications)',
    normal: 'Normal',
    hilarious: 'Hilarious (Egyptian Style)',
    shiftSchedule: 'Shift Schedule',
    team: 'Team',
    offDuty: 'Off Duty',
    dailyLog: "Today's Log (Lined Paper Style)",
    submitEntry: "Submit Entry (اعتماد يا ريس!)",
    entryPlaceholder: "What's cookin' today, chief? (اكتب هنا يا كبير)",
    viewTeamDetails: "View Team Details",
    hideTeamDetails: "Hide Team Details",
    pumpName: "Pump Name",
    pumpStatus: "Pump Status",
    running: "Running",
    standby: "Standby",
    maintenance: "Maintenance",
    offline: "Off",
    activeShift: "Active Shift",
    upcomingShift: "Upcoming Shift",
    loadingMessage: "Loading, ya masta...",
    splashIntro: "UGDCO - Petroleum's Finest!",
    prayerTimes: "Prayer Times",
    prayerTimesDamietta: "Prayer Times (Damietta) - Mock",
    fajr: "Fajr",
    dhuhr: "Dhuhr",
    asr: "Asr",
    maghrib: "Maghrib",
    isha: "Isha",
    salaryNotification: "Salary Notification",
    salaryNotificationToggle: "Remind me when the salary drops (for the party!)",
    salaryNotificationEnabledMessage: "Great! We'll ping you when the moolah arrives!",
    quickActions: "Quick Actions",
    requestLeave: "Request Leave", 
    funStuff: "Fun Stuff",
    funStuffTitle: "Break Time - Entertainment Zone",
    quranRadio: "Quran Radio (Cairo)",
    quranRadioPlayerTitle: "Quran Radio from Cairo",
    quranRadioNowPlaying: "Now Playing: Live Stream",
    quranRadioPlay: "Play",
    quranRadioPause: "Pause",
    quranRadioLoading: "Loading Stream...",
    quranRadioError: "Error Playing Stream",
    quranRadioPlaying: "Playing Now",
    quranRadioPaused: "Paused",
    puzzleGame: "Petroleum Puzzle (AI Powered!)", 
    puzzleGameTitle: "Brain Teaser!",
    puzzleGamePlay: "Play Puzzle",
    puzzleGameQuestion: "What is the primary component of Natural Gas?", 
    puzzleGameOptA: "A) Ethane", 
    puzzleGameOptB: "B) Methane", 
    puzzleGameOptC: "C) Propane", 
    puzzleGameSubmit: "Submit Answer",
    puzzleGameCorrect: "Correct! You're a genius!",
    puzzleGameWrong: "Oops! Nice try, Einstein!",
    jokesToday: "Jokes of the Day (AI Generated!)", 
    chatbotFahlawy: "Chat with 'El Fahlawy'",
    chatbotPlaceholder: "Ask El Fahlawy anything...",
    chatbotSend: "Send",
    chatbotDefaultResponse1: "Leave me alone, I'm still learning!",
    chatbotDefaultResponse2: "That's a tough one... needs a coffee break!",
    chatbotDefaultResponse3: "Ask me something easier, champ!",
    import: "Import",
    export: "Export",
    docked: "Docked",
    anchored: "Anchored",
    dailyTaskPrompt: "Log everything, chief! Every task counts. 💪",
    shipManagementFooter: "Ship management is an art! Pay attention to every detail.",
    settingsFooter: "Adjust your settings as you like, as long as the work gets done right!",
    sidebarFooter: "Control Shift Pro © {year}\n{appName} - {companyShortName}", 
    globalFooter: "Programming and Development by Ahmed Darwish | أحمد درويش © {year}", 
    dashboardGreeting: "Good Morning/Evening depending on your shift! Control Shift Pro at your service, boss.",
    dailyCoffeeStat: "Daily coffee consumption: 500 cups. Keep it up, guys!",
    shiftFocusMessage: "Focus up, champ, this shift is yours!",
    shiftEnjoyBreak: "Team is off duty. Enjoy your break!",
    taskPointsMessage: "Finish 5 taskies and get a star!",
    shipDockedMessage: "This ship is under our watch, no worries!",
    noShipsFunny: "Looks like the navy took a day off today... 😂",
    settingsRolePrompt: "This is your role in the gig, choose wisely for correct permissions!",
    settingsThemePrompt: "Day mode for your beautiful eyes, Night mode when it gets dark.",
    settingsComedyPrompt: "Want your notifications serious or hilarious? 😉",
    settingsPrayerPrompt: "Prayer times - so God blesses us.",
    settingsPrayerReminderButton: "Remind me 10 mins before",
    settingsPrayerReminderSet: "Done, boss! We'll buzz you before prayer.",
    settingsWhatsAppTelegram: "Link Notifications with WhatsApp/Telegram",
    settingsLinkWhatsApp: "Link with WhatsApp",
    settingsLinkTelegram: "Link with Telegram",
    settingsLinkSoon: "Stay connected! Link your accounts for direct notifications.",
    viewName_dashboard: "Dashboard",
    viewName_shifts: "Shifts",
    viewName_tasks: "Daily Log",
    viewName_ships: "Ships",
    viewName_fun: "Fun Zone",
    viewName_settings: "Settings",
    viewName_leaveRequest: "Leave Request",
    viewName_chat: "Team Chat",
    viewName_kanban: "Recurring Tasks", 
    viewName_profile: "My Profile",
    viewName_preventiveMaintenance: "Preventive Maintenance",
    viewName_accidentReport: "Accident Reports",
    viewName_login: "Login",
    viewName_signup: "Sign Up",
    kanbanBoardTitle: "Recurring Tasks - Stay on Top of Your Routines", 
    kanbanTodo: "Scheduled (Ready to Go)", 
    kanbanInProgress: "Active (Currently Doing)", 
    kanbanDone: "Completed (All Set!)", 
    kanbanSampleTask1Title: "Daily Equipment Check", 
    kanbanSampleTask1Desc: "Inspect main pumps and compressors for anomalies.", 
    kanbanSampleTask2Title: "Weekly Safety Log Review", 
    kanbanSampleTask2Desc: "Ensure all safety logs from the past week are complete and signed.", 
    kanbanSampleTask3Title: "Monthly Backup Generator Test", 
    kanbanSampleTask3Desc: "Run the backup generator for 30 minutes under load.", 
    kanbanSampleTask4Title: "Shift Handover Checklist", 
    kanbanSampleTask4Desc: "Complete all items on the shift handover checklist before leaving.", 
    kanbanSampleTask5Title: "Quarterly Fire Drill Report", 
    kanbanSampleTask5Desc: "Compile and submit the quarterly fire drill report.", 
    kanbanSampleTask6Title: "Annual System Calibration", 
    kanbanSampleTask6Desc: "Schedule and oversee annual calibration of critical monitoring systems.", 
    kanbanMoveTask: "Move to Next Stage",
    kanbanFooter: "Keep your recurring tasks in check! Consistency is key, champ.", 
    petroleumFlame: "Petroleum Flame",
    ugdcWelcome: "United Gas Derivatives Company Welcomes You!",
    footerCompanyName: "United Gas Derivatives Company",
    myProfile: "My Profile",
    logout: "Logout",
    logoutSuccess: "Logged out successfully. See you soon, champ!", 
    leaveRequestTitle: "Request Time Off",
    leaveRequestDescription: "Use this form to request vacation or sick leave.", 
    chatTitle: "Team Chat",
    chatDescription: "Connect with your colleagues.", 
    shipNameNefertiti: '"Nefertiti" The Beauty',
    shipNameAbuSaree: '"Abu Saree3" Gas Rocket',
    shipNameOmHashem: '"Om Hashem" The Blessed',
    pumpSpareName: 'Spare Pump "El Nenna"',
    pumpPamperedName: 'Pampered Pump',
    pumpBossRedaName: 'Boss Reda\'s Pump',
    comingSoon: "Coming Soon!", 
    comingSoonMessage: "We're cooking something awesome here!", 
    featureUnderConstruction: "This feature is still under construction, boss!", 
    settingsChangeSuccess: "Settings updated successfully, ya rayyes!",
    leaveRequestSubmitSuccess: "Leave request submitted for review, ya batal!",
    chatMessageSent: "Message sent to the team, ya wa7sh!",
    preventiveMaintenanceTitle: "Preventive Maintenance Schedule (Keep equipment happy!)",
    preventiveMaintenanceEquipmentList: "Equipment List",
    preventiveMaintenanceScheduleMaintenance: "Schedule Maintenance",
    preventiveMaintenanceUpcoming: "Upcoming Maintenance",
    preventiveMaintenanceNoUpcoming: "No upcoming maintenance. Everything is shiny!",
    preventiveMaintenanceFooter: "A stitch in time saves nine... and a lot of downtime!",
    accidentReportTitle: "Accident/Incident Reports (Safety First!)",
    accidentReportFormTitle: "Report New Incident",
    accidentReportDate: "Date of Incident",
    accidentReportLocation: "Location",
    accidentReportType: "Type of Incident",
    accidentReportDescription: "Describe what happened...",
    accidentReportSubmit: "Submit Report",
    accidentReportRecent: "Recently Reported Incidents",
    accidentReportNoRecent: "No recent incidents. Keep up the safe work!",
    accidentReportFooter: "Reporting helps us learn and prevent future ouchies.",
    recurringTasksSectionTitle: "Recurring Tasks (Don't Forget These!)",
    recurringTaskCheckValves: "Confirm all critical valves are closed.",
    recurringTaskGeneratorOil: "Check generator oil level.",
    recurringTaskSafetyBriefing: "Conduct pre-shift safety briefing.",
    puzzleFetchingError: "Oops! Couldn't fetch a new puzzle. Try again!",
    jokeFetchingError: "Aywa ya captain! Couldn't fetch a new joke. The AI might be on a tea break.",
    noNotifications: "No new notifications at the moment.",
    profileNameLabel: "Name",
    profileRoleLabel: "Role",
    profileTeamLabel: "Team",
    profileEmailLabel: "Email",
    profilePhoneLabel: "Phone",
    profileLastLoginLabel: "Last Login",
    profileEditButton: "Edit Profile",
    profileChangePasswordButton: "Change Password",
    profileNotificationSettingsButton: "Notification Settings",
    profileFeatureDevToast: "This specific profile feature ({featureName}) is still under development, boss!",
    profileFooterActive: "Your profile page is active! Some specific actions are still being fine-tuned.",
    profileEditInfoTitle: "Edit Your Information",
    profileChangePasswordTitle: "Change Your Password",
    profileNotificationSettingsTitle: "Notification Preferences",
    profileCurrentPasswordLabel: "Current Password",
    profileNewPasswordLabel: "New Password",
    profileConfirmNewPasswordLabel: "Confirm New Password",
    profileCurrentPasswordPlaceholder: "Enter current password",
    profileNewPasswordPlaceholder: "Enter new password",
    profileConfirmNewPasswordPlaceholder: "Confirm new password",
    profileSaveChangesButton: "Save Changes",
    profileUpdatePasswordButton: "Update Password",
    profileSaveNotificationPrefsButton: "Save Preferences",
    profileCancelButton: "Cancel",
    profileNotifyEmailShiftsLabel: "Email Notifications for Shifts",
    profileNotifyPushTasksLabel: "Push Notifications for Tasks",
    profileNotifySmsAlertsLabel: "SMS Alerts for Critical Issues",
    profileUpdateSuccess: "Profile updated successfully, boss!",
    profilePasswordChangeSuccess: "Password changed successfully (simulated), ya rayyes!",
    profileNotificationSettingsSuccess: "Notification settings saved, chief!",
    profileFooterEdit: "Carefully update your information and save.",
    linkWithWhatsAppTitle: "Link with WhatsApp",
    linkWithTelegramTitle: "Link with Telegram",
    linkQrCodeAlt: "QR Code for linking",
    linkInstructionsWhatsApp: "Scan this QR code with WhatsApp to link your account for notifications.",
    linkInstructionsTelegram: "Open Telegram, search for our bot, and use this code to link.",
    linkConfirmButton: "Confirm Link (Mock)",
    linkCancelButton: "Cancel",
    linkSuccessWhatsAppToast: "WhatsApp linked successfully (mock)!",
    linkSuccessTelegramToast: "Telegram linked successfully (mock)!",
    loginTitle: "Login to Control Shift Pro",
    signupTitle: "Create New Account",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    loginButton: "Login",
    signupButton: "Sign Up",
    dontHaveAccountPrompt: "Don't have an account? Sign Up",
    alreadyHaveAccountPrompt: "Already have an account? Login",
    loginFailedError: "Login failed. Please check your email and password.",
    loginFailedNetworkError: "Login failed due to a network issue. Please check your internet connection and try again.",
    signupFailedError: "Signup failed. Please try again. The email might be in use or password too weak.",
    logoutFailedError: "Logout failed. Please try again.",
    passwordResetPrompt: "Forgot Password?",
    passwordResetSentSuccess: "Password reset email sent! Check your inbox.",
    passwordResetSentError: "Failed to send password reset email. Please try again.",
    profileDataLoadError: "Failed to load your profile data. Please check your connection and try again.",
    funStuffApiKeyMissingPuzzle: "ألغاز الذكاء الاصطناعي تستخدم محتوى تجريبي. (مفتاح الواجهة البرمجية غير مهيأ)",
    funStuffApiKeyMissingJoke: "نكت الذكاء الاصطناعي من قائمة تجريبية. (مفتاح الواجهة البرمجية غير مهيأ)",
    errorModalDefaultTitle: "Application Error",
    errorModalCloseButton: "Close",
  },
  [Language.AR]: {
    appName: APP_NAME_AR,
    companyName: COMPANY_NAME_AR,
    dashboard: 'الرئيسية (وش القفص)',
    shifts: 'الورديات (مين عليه الدور؟)',
    tasks: 'شغل اليوم (إنجز وخلص)',
    ships: 'المراكب (أسطول الخير)',
    settings: 'الضبط (على كيفك)',
    notifications: 'الإشعارات',
    language: 'اللغة (عشان نتكلم نفس الموجة)',
    english: 'إنجليزي (لو حابب تتفزلك)',
    arabic: 'عربي (لغة الضاد يا جدعان)',
    welcomeMessage: `يا صباح/مساء الفل حسب ورديتك! ${APP_NAME_AR} تحت أمرك يا ريّس. يلا بينا نولع الدنيا شغل!`,
    currentShift: 'الوردية الشغالة حالياً',
    morningShift: `وردية الصنفره (${MORNING_SHIFT_START} - ${MORNING_SHIFT_END})`,
    eveningShift: `وردية السهرة صباحي (${EVENING_SHIFT_START} - ${EVENING_SHIFT_END})`,
    teamOnDuty: 'الفريق اللي عليه الدور',
    supervisor: 'الأسطى الكبير (المشرف)',
    members: ' الرجالة (الأعضاء)',
    addTask: 'ضيف таسكاية جديدة',
    taskDescription: 'هتعمل إيه بالظبط؟ احكي...',
    saveTask: 'كله تمام، سجل يا ابني!',
    noTasks: 'مفيش شغل النهاردة ولا إيه؟ الدنيا نايمة خالص... قوموا يا رجالة ورونا الهمة!',
    shipName: 'اسم المركب (الأصل)',
    shipStatus: 'إيه أخبارها؟ (الحالة)',
    cargoType: 'شاحنة إيه؟ (نوع الشحنة)',
    quantityRemaining: 'فاضل قد إيه؟',
    quantityPerHour: 'المعدل كام في الساعة؟',
    eta: 'هتوصل/هتمشي امتى؟ (متتأخرش علينا)',
    pumps: 'المضخات (قلب الشغلانة)',
    noShips: 'البحر فاضي النهاردة، شكل السمك واخد إجازة! 😂 ولا مفيش مراكب جاية؟',
    userRole: 'انت مين في الليلة دي؟ (دور المستخدم)',
    selectRole: 'قولنا انت مين عشان نظبطلك الدنيا',
    employee: 'موظف (جندي مجهول)',
    supervisorRole: 'مشرف (الأسطى الكبير)',
    engineer: 'مهندس (أبو التفانين)',
    engineersList: 'المهندسين (بتوع الاختراعات)',
    supervisorsList: 'المشرفين والفرق (كباتن الفرق)',
    appTheme: 'شكل البرنامج (المود بتاعك)',
    lightMode: 'مود النهار (عشان عينيك الحلوة)',
    darkMode: 'مود السهرة (لما الدنيا تليل)',
    darkModeDescription: 'لجماعة السهارى والناس الرايقة.',
    comedyLevel: 'مستوى الضحك في الإشعارات (عشان متزهقش)',
    normal: 'عادي (كلام جد)',
    hilarious: 'هتموت من الضحك (فكّها يا عم)',
    shiftSchedule: 'جدول النوبتجيات - مين عليه الليلة؟',
    team: 'الفريق (الشلة)',
    offDuty: 'أنتيم (خارج الخدمة، خدلك راحة)',
    dailyLog: "ورقة شغل اليوم - اكتب إنجازاتك يا فنان!",
    submitEntry: "اعتمد يا كبير!",
    entryPlaceholder: "ناوي على إيه النهاردة يا بطل؟ (اكتب هنا إبداعاتك)",
    viewTeamDetails: "ورينا تفاصيل الفريق كده",
    hideTeamDetails: "خلاص يا عم، اخفي التفاصيل",
    pumpName: "اسم المضخة (بتاعة مين دي؟)",
    pumpStatus: "حالتها إيه المضخة دي؟",
    running: "شغالة زي الفل",
    standby: "استبن (جاهزة للطوارئ)",
    maintenance: "بتتدلع (في الصيانة)",
    offline: "نايمة (متوقفة)",
    activeShift: "الوردية الشغالة",
    upcomingShift: "الوردية اللي جاية (استعد)",
    loadingMessage: "بنحمّل البرنامج يا ريس... كلها ثواني وتلاقي الدنيا ظبطت!",
    splashIntro: `${APP_NAME_AR} - رجالة بترول دمياط الأبطال!`,
    prayerTimes: "مواقيت الصلاة (عشان ربنا يكرم)",
    prayerTimesDamietta: "مواقيت الصلاة (دمياط) - (لسه بنظبطها)",
    fajr: "الفجر (قوم صحصح)",
    dhuhr: "الضهر (صلي الظهر وأنت فايق)",
    asr: "العصر (العصر أذن يا مولانا)",
    maghrib: "المغرب (المغرب خلاص أهو)",
    isha: "العشاء (العشا أذنت يلا نصلي)",
    salaryNotification: "تنبيه المرتب (أهم حاجة)",
    salaryNotificationToggle: "فكرني لما المرتب ينزل (عشان الحفلة بقى!)",
    salaryNotificationEnabledMessage: "أبشر يا غالي! أول ما المرتب يهلّ هنبعتلك رسالة تفرح قلبك وتخليك تعزمنا على حاجة ساقعة!",
    quickActions: "إنجز مهامك (دوس هنا وخلص)",
    requestLeave: "اطلب إجازة", 
    funStuff: "شوية دلع (فك عن نفسك)",
    funStuffTitle: "فاصل ونواصل - شوية ترفيه عشان الزهق ميمسكش فيك",
    quranRadio: "إذاعة القرآن الكريم من القاهرة (سكينة وراحة بال)",
    quranRadioPlayerTitle: "إذاعة القرآن الكريم من القاهرة",
    quranRadioNowPlaying: "الآن بث مباشر",
    quranRadioPlay: "شغل يا حاج",
    quranRadioPause: "وقف يا عم الشيخ",
    quranRadioLoading: "جارى التحميل...",
    quranRadioError: "خطأ في تشغيل الإذاعة للأسف... جرب رابط تاني أو شوف النت.",
    quranRadioPlaying: "شغالة زي الحلاوة",
    quranRadioPaused: "وقفتها يا برنس",
    puzzleGame: "لعبة ذكاء بترولية (بالذكاء الاصطناعي!)", 
    puzzleGameTitle: "فزورة بترولية على السريع!",
    puzzleGamePlay: "العب الفزورة",
    puzzleGameQuestion: "ما هو المكون الأساسي للغاز الطبيعي؟", 
    puzzleGameOptA: "أ) الإيثان", 
    puzzleGameOptB: "ب) الميثان", 
    puzzleGameOptC: "ج) البروبان", 
    puzzleGameSubmit: "ابعت إجابتك يا فنان",
    puzzleGameCorrect: "صح الصح يا برنس! أنت كده فاهم الشغلانة!",
    puzzleGameWrong: "إجابة غلط يا كبير! حاول تاني يمكن تصيب معاك.",
    jokesToday: "نكت اليوم (من إنتاج الذكاء الاصطناعي!)", 
    chatbotFahlawy: "دردش مع 'الفهلوي' (الواد اللماح)",
    chatbotPlaceholder: "اسأل الفهلوي أي سؤال يخطر في بالك...",
    chatbotSend: "ابعتله",
    chatbotDefaultResponse1: "يا عم سيبني في حالي أنا لسه بتعلم وبجمع معلومات!",
    chatbotDefaultResponse2: "سؤالك ده محتاج قاعدة وفنجان قهوة عشان أجاوبك عليه صح!",
    chatbotDefaultResponse3: "بصراحة سؤالك صعب، اسألني حاجة أسهل كده أكون عارفها.",
    import: "استيراد (جايلنا بضاعة)",
    export: "تصدير (موديين بضاعة)",
    docked: "راكنة بتتأمل (مركونة في المينا)",
    anchored: "مستنية دورها (مرساة بره)",
    dailyTaskPrompt: "سجل يا تاريخ، كل مهمة بتعملها بتفرق! 💪 ورينا شغلك يا فنان!",
    shipManagementFooter: "إدارة المراكب دي فن مش عن عن! خلي بالك من كل تفصيلة عشان الدنيا تمشي زي الساعة.",
    settingsFooter: "ظبط إعداداتك براحتك يا معلم، المهم الشغل يطلع مية مية ومزاجك يكون رايق!",
    sidebarFooter: "{appName} © {year}\n{companyShortName} - الشغل عايز ناس فايقة!", 
    globalFooter: "جميع حقوق البرمجه والتطوير بواسطة أحمد درويش | Ahmed Darwish © {year}", 
    dashboardGreeting: "يا صباح/مساء الخيرات والليرات! كنترول شيفت برو تحت أمر جلالتك.",
    dailyCoffeeStat: "معدل حرق البن اليومي في الموقع: ٥٠٠ فنجان قهوة وشاي. شدوا حيلكم يا وحوش!",
    shiftFocusMessage: "ركز معانا يا بطل، الوردية دي بتاعتك وفيها كل خير إن شاء الله!",
    shiftEnjoyBreak: "الفريق في راحة يا محظوظ! روح انبسط وغير جو, تستاهل كل خير.",
    taskPointsMessage: "خلص خمس таскаيات كده على السريع وخد نجمة منورة زي وشك!",
    shipDockedMessage: "المركب دي تحت عنينا وفي حمايتنا، متقلقش من أي حاجة كل حاجة كنترول!",
    noShipsFunny: "المينا فاضية ليه يا جدعان؟ شكل المراكب كلها راحت تصيف في الساحل الشمالي! 😂",
    settingsRolePrompt: "حدد دورك في المنظومة يا ريس، عشان كل واحد يعرف اللي ليه واللي عليه.",
    settingsThemePrompt: "اختار مود النهار لو عينك مزغللة، أو مود السهرة لو بتحب الروقان والهدوء.",
    settingsComedyPrompt: "تحب الإشعارات تجيلك ناشفة ولا مليانة ضحك وهزار؟ اختار اللي يريح نفسيتك.",
    settingsPrayerPrompt: "مواقيت الصلاة عشان متفوتش فرض وربنا يكرمنا جميعاً في رزقنا وشغلنا.",
    settingsPrayerReminderButton: "فكرني قبلها بـ 10 دقايق",
    settingsPrayerReminderSet: "تم يا ريس! أول ما الأذان يقرب هنديلك جرس.",
    settingsWhatsAppTelegram: "ربط الإشعارات بالواتس/تليجرام (عشان متفوتكش فايتة)",
    settingsLinkWhatsApp: "اربط مع الواتساب",
    settingsLinkTelegram: "اربط مع التليجرام",
    settingsLinkSoon: "خليك متواصل دايماً! اربط حساباتك عشان الإشعارات تجيلك على طول.",
    viewName_dashboard: "الرئيسية", 
    viewName_shifts: "الورديات", 
    viewName_tasks: "مهام يومية", 
    viewName_ships: "المراكب", 
    viewName_fun: "ترفيه", 
    viewName_settings: "الضبط", 
    viewName_leaveRequest: "طلب إجازة",
    viewName_chat: "شات الفريق", 
    viewName_kanban: "المهمات الدورية", 
    viewName_profile: "ملفي الشخصي",
    viewName_preventiveMaintenance: "صيانة وقائية", 
    viewName_accidentReport: "تقارير حوادث",
    viewName_login: "تسجيل الدخول",
    viewName_signup: "إنشاء حساب جديد",
    kanbanBoardTitle: "المهمات الدورية - خليك مسيطر على روتينك اليومي", 
    kanbanTodo: "مجدولة (جاهزة للتنفيذ)", 
    kanbanInProgress: "نشطة (جاري العمل عليها)", 
    kanbanDone: "مكتملة (كله تمام!)", 
    kanbanSampleTask1Title: "فحص المعدات اليومي", 
    kanbanSampleTask1Desc: "تفقد المضخات والكمبروسرات الرئيسية بحثاً عن أي مشاكل.", 
    kanbanSampleTask2Title: "مراجعة سجلات السلامة الأسبوعية", 
    kanbanSampleTask2Desc: "التأكد من اكتمال وتوقيع جميع سجلات السلامة للأسبوع الماضي.", 
    kanbanSampleTask3Title: "اختبار المولد الاحتياطي الشهري", 
    kanbanSampleTask3Desc: "تشغيل المولد الاحتياطي لمدة ٣٠ دقيقة تحت الحمل.", 
    kanbanSampleTask4Title: "قائمة مراجعة تسليم الوردية", 
    kanbanSampleTask4Desc: "إكمال جميع بنود قائمة مراجعة تسليم الوردية قبل المغادرة.", 
    kanbanSampleTask5Title: "تقرير تدريب الحريق الربع سنوي", 
    kanbanSampleTask5Desc: "تجميع وتقديم تقرير تدريب الحريق الربع سنوي.", 
    kanbanSampleTask6Title: "معايرة النظام السنوية", 
    kanbanSampleTask6Desc: "جدولة والإشراف على المعايرة السنوية لأنظمة المراقبة الحرجة.", 
    kanbanMoveTask: "انقلها للمرحلة الجاية يا ريس",
    kanbanFooter: "حافظ على مهامك الدورية تحت السيطرة! الاستمرارية هي مفتاح النجاح يا بطل.", 
    petroleumFlame: "شعلة بترول الغاز الطبيعي",
    ugdcWelcome: "الشركة المتحدة لمشتقات الغاز موقع دمياط ترحب بالسادة العاملين!",
    footerCompanyName: "الشركة المتحدة لمشتقات الغاز",
    myProfile: "ملفي الشخصي", 
    logout: "تسجيل الخروج",
    logoutSuccess: "تم تسجيل الخروج بنجاح. نشوفك على خير يا بطل!", 
    leaveRequestTitle: "طلب إجازة",
    leaveRequestDescription: "استخدم النموذج ده عشان تطلب إجازة سواء اعتيادية أو مرضية.", 
    chatTitle: "شات الرجالة",
    chatDescription: "اتكلم مع زمايلك وفضفض براحتك.", 
    chatMessageSent: "الرسالة وصلت للفريق يا وحش!",
    shipNameNefertiti: 'الأمورة " نفرتيتي "',
    shipNameAbuSaree: 'صاروخ الغاز " أبو سريع "',
    shipNameOmHashem: 'البركة " أم هاشم "',
    pumpSpareName: 'مضخة سبير احتياطي الننا',
    pumpPamperedName: 'مضخة بتدلع شوية',
    pumpBossRedaName: 'مضخة المعلم رضا',
    comingSoon: "قريباً إن شاء الله!",
    comingSoonMessage: "بنطبخ حاجة على نار هادية هتعجبك!",
    featureUnderConstruction: "الميزة دي لسه في الفرن، أول ما تستوي هنقولك!",
    settingsChangeSuccess: "تم حفظ التعديلات بنجاح يا ريس!",
    leaveRequestSubmitSuccess: "طلبك اتبع للحسابات يا بطل، وإن شاء الله خير!",
    preventiveMaintenanceTitle: "جدول الصيانة الوقائية (عشان المعدات متزعلش مننا وتقفش في وقت زنقة)",
    preventiveMaintenanceEquipmentList: "قائمة المعدات (اللي محتاجة حنية)",
    preventiveMaintenanceScheduleMaintenance: "اعملها صيانة وقائية يا أسطى",
    preventiveMaintenanceUpcoming: "الصيانات اللي جاية في السكة",
    preventiveMaintenanceNoUpcoming: "كله تمام وزي الفل، مفيش صيانات جاية قريب. المعدات واكله شاربه نايمه!",
    preventiveMaintenanceFooter: "الصيانة في وقتها بتوفر فلوس ووقت... ووجع دماغ!",
    accidentReportTitle: "تقارير الحوادث (سلامتك أهم من الشغل ومليون برميل بترول)",
    accidentReportFormTitle: "سجل يا تاريخ الواقعة الجديدة",
    accidentReportDate: "تاريخ الواقعة (يوم ما النور طفا)",
    accidentReportLocation: "مكان الحادثة (فين بالظبط؟)",
    accidentReportType: "نوع الواقعة (خير اللهم اجعله خير)",
    accidentReportDescription: "احكيلي إيه اللي حصل بالتفصيل الممل...",
    accidentReportSubmit: "اعتمد التقرير يا كبير",
    accidentReportRecent: "آخر الوقائع المسجلة (عشان نتعلم)",
    accidentReportNoRecent: "الحمد لله مفيش حوادث جديدة. ربنا يسترها علينا دايماً!",
    accidentReportFooter: "تسجيل الحوادث بيساعدنا نتفادى المشاكل في المستقبل ونحافظ على سلامة الكل.",
    recurringTasksSectionTitle: "تاسكات بتتكرر كل يوم (متنسهاش يا صاحبي!)",
    recurringTaskCheckValves: "تأكيد إغلاق الصمامات الحرجة (مهم أوي!).",
    recurringTaskGeneratorOil: "فحص مستوى زيت المولد (عشان ميقفش فجأة).",
    recurringTaskSafetyBriefing: "اجتماع السلامة بتاع قبل الوردية (ركز فيه).",
    puzzleFetchingError: "أوبس! معرفناش نجيب فزورة جديدة. حاول تاني يا بطل!",
    jokeFetchingError: "أيوه يا كابتن! معرفناش نجيب نكتة جديدة. الذكاء الاصطناعي ممكن يكون واخد بريك شاي.",
    noNotifications: "لا توجد إشعارات جديدة حالياً.",
    profileNameLabel: "الاسم بالكامل",
    profileRoleLabel: "المنصب / الدور",
    profileTeamLabel: "الفريق البطل",
    profileEmailLabel: "الإيميل الرسمي",
    profilePhoneLabel: "رقم الموبايل",
    profileLastLoginLabel: "آخر مرة نورتنا",
    profileEditButton: "تعديل بياناتي الشخصية",
    profileChangePasswordButton: "تغيير كلمة المرور",
    profileNotificationSettingsButton: "ضبط إشعاراتي",
    profileFeatureDevToast: "يا ريس، الخاصية دي ({featureName}) لسه بتستوي على نار هادية وهتكون جاهزة قريب!",
    profileFooterActive: "صفحتك الشخصية منورة يا كبير! بعض الأكشنات جواها لسه بنحط عليها التاتش الأخير.",
    profileEditInfoTitle: "تعديل معلوماتك الشخصية",
    profileChangePasswordTitle: "تغيير كلمة المرور بتاعتك",
    profileNotificationSettingsTitle: "إعدادات الإشعارات والتنبيهات",
    profileCurrentPasswordLabel: "كلمة المرور الحالية",
    profileNewPasswordLabel: "كلمة المرور الجديدة",
    profileConfirmNewPasswordLabel: "تأكيد كلمة المرور الجديدة",
    profileCurrentPasswordPlaceholder: "دخل كلمة مرورك الحالية هنا",
    profileNewPasswordPlaceholder: "اكتب كلمة مرور جديدة وقوية",
    profileConfirmNewPasswordPlaceholder: "اكتب كلمة المرور الجديدة تاني",
    profileSaveChangesButton: "حفظ التعديلات",
    profileUpdatePasswordButton: "تحديث كلمة المرور",
    profileSaveNotificationPrefsButton: "حفظ إعدادات الإشعارات",
    profileCancelButton: "إلغاء",
    profileNotifyEmailShiftsLabel: "إشعارات البريد الإلكتروني للورديات الجديدة",
    profileNotifyPushTasksLabel: "إشعارات لحظية للمهام المستعجلة",
    profileNotifySmsAlertsLabel: "رسائل نصية للتنبيهات الحرجة",
    profileUpdateSuccess: "تم تحديث بياناتك بنجاح يا وحش!",
    profilePasswordChangeSuccess: "تم تغيير كلمة المرور بنجاح (بشكل تجريبي)! خليها في سرك.",
    profileNotificationSettingsSuccess: "تم حفظ إعدادات الإشعارات بتاعتك يا فنان!",
    profileFooterEdit: "اتاكد من بياناتك كويس قبل ما تحفظ يا ريس.",
    linkWithWhatsAppTitle: "ربط الحساب بالواتساب",
    linkWithTelegramTitle: "ربط الحساب بالتليجرام",
    linkQrCodeAlt: "صورة كود QR للربط",
    linkInstructionsWhatsApp: "امسح الكود ده بكاميرا الواتساب عشان تربط حسابك وتجيلك الإشعارات على طول.",
    linkInstructionsTelegram: "افتح برنامج التليجرام، وابحث عن البوت بتاعنا، وبعدين استخدم الكود ده للربط.",
    linkConfirmButton: "تأكيد الربط (تجريبي)",
    linkCancelButton: "إلغاء الأمر",
    linkSuccessWhatsAppToast: "تم ربط حسابك بالواتساب بنجاح (تجريبي)! الإشعارات هتجيلك لحد عندك.",
    linkSuccessTelegramToast: "تم ربط حسابك بالتليجرام بنجاح (تجريبي)! جهز نفسك لسيل من الإشعارات.",
    loginTitle: "تسجيل الدخول - كنترول شيفت برو",
    signupTitle: "إنشاء حساب جديد في كنترول شيفت برو",
    emailLabel: "البريد الإلكتروني (الإيميل بتاع الشغل)",
    passwordLabel: "كلمة المرور (متقولهاش لحد!)",
    confirmPasswordLabel: "تأكيد كلمة المرور (اكتبها تاني)",
    loginButton: "دخول يا ريس!",
    signupButton: "إنشاء حساب جديد يلا بينا!",
    dontHaveAccountPrompt: "معندكش حساب لسه؟ اعمل واحد جديد من هنا",
    alreadyHaveAccountPrompt: "عندك حساب بالفعل؟ سجل دخولك من هنا",
    loginFailedError: "فشلت عملية تسجيل الدخول. اتأكد من الإيميل وكلمة المرور يا بطل.",
    loginFailedNetworkError: "فشلت عملية تسجيل الدخول بسبب مشكلة في الشبكة. من فضلك تحقق من اتصالك بالإنترنت وحاول مرة أخرى.",
    signupFailedError: "فشلت عملية إنشاء الحساب. حاول تاني، يمكن الإيميل مستخدم قبل كده أو كلمة المرور ضعيفة شوية.",
    logoutFailedError: "فشلت عملية تسجيل الخروج. حاول مرة تانية.",
    passwordResetPrompt: "نسيت كلمة المرور؟ (ولا يهمك بتحصل)",
    passwordResetSentSuccess: "تم إرسال إيميل إعادة تعيين كلمة المرور! شيك على بريدك.",
    passwordResetSentError: "فشل إرسال إيميل إعادة تعيين كلمة المرور. حاول تاني بعد شوية.",
    profileDataLoadError: "فشل تحميل بيانات ملفك الشخصي. يرجى التحقق من اتصالك والمحاولة مرة أخرى.",
    funStuffApiKeyMissingPuzzle: "ألغاز الذكاء الاصطناعي تستخدم محتوى تجريبي. (مفتاح الواجهة البرمجية غير مهيأ)",
    funStuffApiKeyMissingJoke: "نكت الذكاء الاصطناعي من قائمة تجريبية. (مفتاح الواجهة البرمجية غير مهيأ)",
    errorModalDefaultTitle: "خطأ في التطبيق",
    errorModalCloseButton: "إغلاق",
  },
};